version: '3.2'

services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - flask
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
      - ./scripts/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt



  flask:
    build:
      context: .
      dockerfile: Dockerfile
    image: subigya/codium_learn:latest
    environment:
     - FLASK_APP=main.py
    command: flask run --host=0.0.0.0

